[package]
name = "planty"
version = "0.1.0"
authors = ["David Steiner <david_j_steiner@yahoo.co.nz>"]
edition = "2018"

[dependencies]
itertools = "0.9.0"
nalgebra = "0.20"
pest = "2.1"
pest_derive = "2.1"
svg = "0.7"