
program = _{ SOI ~ "\n"* ~ "@startuml" ~ "\n"+ ~ (stmt ~ "\n"+)* ~ "@enduml" ~ "\n"* ~ EOI }

stmt = {
      participant
    | message
}

arrow = { "->" | "-->" | "<--" | "<-" }
participant = { "participant" ~ ident }

label = { (!"\n" ~ ANY)* }
message_label = { ":" ~ label }
message = { ident ~ arrow ~ ident ~ message_label? }
ident = @{ ASCII_ALPHA ~ (ASCII_ALPHANUMERIC | "_")* }


WHITESPACE = _{ " " | "\t" }
